### ISSUE TITLE
Halfmoon script 'T' is coloured purple despite only having one option

### ISSUE THREAD

**Issue by Starwort** [kerfuzzle/decipher.ink#4]
![Screenshot_20240331-140700.png](https://github.com/kerfuzzle/decipher.ink/assets/16487249/a06d17c6-8e09-456f-b9c7-306489a92374)

# What happens

T (coloured purple) has no permutations and according to the source file has only 1 value; A (also coloured purple) has 8 permutations (2 per A, A/H), N (coloured black) can only represent N

# What should happen

T should be coloured black, as it only has 1 option

**Comment by kerfuzzle** [comment]
Accidentally had a second mapping for T at the end of the file when it should just be the D/T towards the start of the file, thanks for finding this!
